# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: DockerCompose@0
  displayName: Container registery login
  inputs:
    containerregistrytype: 'Azure Container Registry'
    azureSubscription: 'sb-adopting-msa'
    azureContainerRegistry: 'formee.azurecr.io'
    dockerComposeFile: 'src/Formee/docker-compose.yml'
    action: Build services

- task: DockerCompose@0
  inputs:
    containerregistrytype: 'Azure Container Registry'
    azureSubscription: 'sb-adopting-msa'
    azureContainerRegistry: 'formee.azurecr.io'
    dockerComposeFile: 'src/Formee/docker-compose.yml'
    action: Push services
    includeLatestTag: true
    includeSourceTags: true

- script: docker login azure
  displayName: Login to azure

- script: docker context create aci deployacicontext
  displayName: Deploy aci context

- script: docker context use deployacicontext
  displayName: Use aci context

- script: docker compose up
  displayName: Run containers