# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- deploy

pool:
  vmImage: ubuntu-latest

steps:
- task: DockerCompose@0
  displayName: Container registery login
  inputs:
    containerregistrytype: 'Azure Container Registry'
    azureSubscription: 'sb-adopting-msa'
    azureContainerRegistry: 'formee.azurecr.io'
    dockerComposeFile: 'src/Formee/docker-compose.yml'
    action: Build services

- task: DockerCompose@0
  inputs:
    containerregistrytype: 'Azure Container Registry'
    azureSubscription: 'sb-adopting-msa'
    azureContainerRegistry: 'formee.azurecr.io'
    dockerComposeFile: 'src/Formee/docker-compose.yml'
    action: Push services
    includeLatestTag: true
    includeSourceTags: true
    
- task: AzureCLI@2
  inputs:
    azureSubscription: 'sb-adopting-msa'
    scriptType: bash
    scriptLocation: 'inlineScript'
    inlineScript: |
      docker login azure
      docker context create aci deployacicontext
      docker context use deployacicontext
      docker compose up