version: "3.8"

services:
  gateway.core:
    image: gateway.core
    build: 
      context: .
      dockerfile: ./Gateways/Gateway.Core/Dockerfile
    expose:
      - "80"
    ports:
      - "5000:80"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
    depends_on:
      - analytics.api
      - containers.api
      - forms.api
      - identity.api
      - links.api

  analytics.api:
    image: analytics.api
    build: 
      context: .
      dockerfile: ./Services/Analytics/Analytics.API/Dockerfile
    expose:
      - "80"
    ports:
      - "5001:80"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: Server=host.docker.internal, 1433;Database=Formee.Analytics;User Id=Admin;Password=Admin@123123;integrated security=false;TrustServerCertificate=True

  containers.api:
    image: containers.api
    build:
      context: .
      dockerfile: ./Services/Containers/API/Dockerfile
    expose:
      - "80"
    ports:
      - "5002:80"
      - "27017:27017"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ContainersDatabase__ConnectionString: mongodb://host.docker.internal:27017/
      ContainersDatabase__DatabaseName: ContainersDatabase
      ContainersDatabase__CollectionName: Containers

  forms.api:
    image: forms.api
    build:
      context: .
      dockerfile: ./Services/Forms/Presentation/Dockerfile
    expose:
      - "80"
    ports:
      - "5003:80"
    environment:
      ASPNETCORE_ENVIRONMENT: development
  
  identity.api:
    image: identity.api
    build:
      context: .
      dockerfile: ./Services/Identity/Identity.API/Dockerfile
    expose:
      - "80"
    ports:
      - "5004:80"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: Server=host.docker.internal, 1433;Database=Formee.Identity;User Id=Admin;Password=Admin@123123;integrated security=false;TrustServerCertificate=True

  links.api:
    image: links.api
    build:
      context: .
      dockerfile: ./Services/Links/Links.API/Dockerfile
    expose:
      - "80"
    ports:
      - "5005:80"
    environment:
      ASPNETCORE_ENVIRONMENT: development

  # livechat.api:
  #   image: livechat.api
  #   build:
  #     context: .
  #     dockerfile: ./Services/LiveChat/Presentation/Dockerfile
  #   expose:
  #     - "80"
  #   ports:
  #     - "5006:80"
  #   environment:
  #     ASPNETCORE_ENVIRONMENT: development
  #     ConnectionStrings__DefaultConnection: Server=livechat.db;Database=Formee.LiveChat;User Id=sa;Password=MyStrongPass123;TrustServerCertificate=true
