version: "3.8"

services:
  client.web:
    container_name: client.web
    build:
      context: .
      dockerfile: "./FrontEnd/Users/Client.Web/Dockerfile"
    profiles: [ "client" ]
    expose:
      - "80"
    ports:
      - "8080:80"
    depends_on:
      - gateway.core

  admin.web:
    container_name: admin.web
    build:
      context: .
      dockerfile: "./FrontEnd/Admins/Admins.Web/Dockerfile"
    profiles: [ "client" ]
    expose:
      - "80"
    ports:
      - "8081:80"
    depends_on:
      - gateway.core
      
  gateway.core:
    container_name: gateway.core
    build: 
      context: .
      dockerfile: ./Gateways/Gateway.Core/Dockerfile
    profiles: [ "service", "gateway" ]
    expose:
      - "80"
    ports:
      - "5000:80"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
    depends_on:
      - containers.service
      - analytics.service
      - forms.service
      - identity.service
      - links.service
      - history.service
      - notifications.service
      - monitoring.service

  analytics.service:
    container_name: analytics.service
    build: 
      context: .
      dockerfile: ./Services/Analytics/Analytics.API/Dockerfile
    profiles: [ "service" ]
    expose:
      - "80"
    ports:
      - "5001:80"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: Server=host.docker.internal, 1433;Database=Formee.Analytics;User Id=Admin;Password=Admin@123123;integrated security=false;TrustServerCertificate=True
      ServiceBus__ConnectionString: Endpoint=sb://formee.servicebus.windows.net/;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=+prGrnIC0RwHSKHF3zJ/5HW35R08KH4wG+ASbPIkqlk=
      ServiceBus__HistoryTopic: topic-history
      ServiceBus__NotificationsTopic: topic-notifications

  containers.service:
    container_name: containers.service
    build:
      context: .
      dockerfile: ./Services/Containers/API/Dockerfile
    profiles: [ "service" ]
    expose:
      - "80"
    ports:
      - "5002:80"
      - "27017:27017"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ContainersDatabase__ConnectionString: mongodb://host.docker.internal:27017/
      ContainersDatabase__DatabaseName: ContainersDatabase
      ContainersDatabase__CollectionName: Containers
      ServiceBus__ConnectionString: Endpoint=sb://formee.servicebus.windows.net/;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=+prGrnIC0RwHSKHF3zJ/5HW35R08KH4wG+ASbPIkqlk=
      ServiceBus__History: topic-history
      ServiceBus__Notifications: topic-notifications
      ServiceBus__NotificationsSubscription: notifications

  forms.service:
    container_name: forms.service
    build:
      context: .
      dockerfile: ./Services/Forms/Presentation/Dockerfile
    profiles: [ "service" ]
    expose:
      - "80"
    ports:
      - "5003:80"
    environment:
      ASPNETCORE_ENVIRONMENT: development
      ConnectionStrings__DefaultConnection: Server=host.docker.internal, 1433;Database=Formee.Forms;User Id=Admin;Password=Admin@123123;integrated security=false;TrustServerCertificate=True
  
  identity.service:
    container_name: identity.service
    build:
      context: .
      dockerfile: ./Services/Identity/Identity.API/Dockerfile
    profiles: [ "service" ]
    expose:
      - "80"
    ports:
      - "5004:80"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: Server=host.docker.internal, 1433;Database=Formee.Identity;User Id=Admin;Password=Admin@123123;integrated security=false;TrustServerCertificate=True
      AzureStorage__ConnectionString: DefaultEndpointsProtocol=https;AccountName=adoptingmsastorage;AccountKey=QNiF+oq3F+EpswAiImlnQINuLurflfMI/EgC+SvqHv/OW9yLJ6+42hm4/W+DipcLK+qpqDk9qHpN+AStIzFf1g==;EndpointSuffix=core.windows.net
      AzureStorage__ContainerName: accountavatars
      Services__Subscriptions: http://host.docker.internal:5007

  links.service:
    container_name: links.service
    build:
      context: .
      dockerfile: ./Services/Links/Links.API/Dockerfile
    profiles: [ "service" ]
    expose:
      - "80"
    ports:
      - "5005:80"
    environment:
      ASPNETCORE_ENVIRONMENT: development
      ConnectionStrings__DefaultConnection: Server=host.docker.internal, 1433;Database=Formee.Links;User Id=Admin;Password=Admin@123123;integrated security=false;TrustServerCertificate=True

  notifications.service:
    container_name: notifications.service
    build:
      context: .
      dockerfile: ./Services/Notifications/Presentation/Dockerfile
    profiles: [ "service" ]
    expose:
      - "80"
    ports:
      - "5006:80"
    environment:
      ASPNETCORE_ENVIRONMENT: development
      ConnectionStrings__DefaultConnection: Server=host.docker.internal, 1433;Database=Formee.Notifications;User Id=Admin;Password=Admin@123123;integrated security=false;TrustServerCertificate=True
      ServiceBus__ConnectionString: Endpoint=sb://formee.servicebus.windows.net/;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=+prGrnIC0RwHSKHF3zJ/5HW35R08KH4wG+ASbPIkqlk=
      ServiceBus__History: topic-history
      ServiceBus__Notifications: topic-notifications
      ServiceBus__NotificationsSubscription: notifications
      ServiceBus__HistorySubscription: history

  subscriptions.service:
    container_name: subscriptions.service
    build:
      context: .
      dockerfile: ./Services/Subscriptions/Subscriptions.API/Dockerfile
    profiles: [ "service" ]
    expose:
      - "80"
    ports:
      - "5007:80"
    environment:
      ASPNETCORE_ENVIRONMENT: development
      ConnectionStrings__DefaultConnection: Server=host.docker.internal, 1433;Database=Formee.Subscriptions;User Id=Admin;Password=Admin@123123;integrated security=false;TrustServerCertificate=True
      
  history.service:
    container_name: history.service
    build:
      context: .
      dockerfile: ./Services/History/Dockerfile
    profiles: [ "service" ]
    expose: 
      - "3000"
    ports:
      - "5008:3000"
    environment:
      AZURE_SERVICE_BUS: Endpoint=sb://formee.servicebus.windows.net/;SharedAccessKeyName=SharedAccessPolicy;SharedAccessKey=2zjgyBu0KGgdOiVx8rHy5GPnHBNvKoR9d+ASbDEu2fw=;EntityPath=topic-history
      MONGO_DB_HISTORY: mongodb://host.docker.internal/history

  monitoring.service:
    container_name: monitoring.service
    profiles: [ "client" ]
    build:
      context: .
      dockerfile: ./Services/Monitoring/Monitoring/Dockerfile
    expose: 
      - "80"
    ports:
      - "5009:80"
    depends_on:
      - analytics.service
      - containers.service
      - forms.service
      - identity.service
      - links.service
      - history.service
      - notifications.service
